import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';

export interface GRNItem {
  id: string;
  grn_id: string;
  po_item_id: string;
  product_id: string | null;
  ordered_quantity: number;
  received_quantity: number;
  accepted_quantity: number;
  rejected_quantity: number;
  rejection_reason: string | null;
  batch_number: string | null;
  notes: string | null;
  created_at: string;
  product?: {
    id: string;
    name: string;
    unit: string | null;
  };
}

export interface GoodsReceiptNote {
  id: string;
  grn_number: string;
  po_id: string;
  supplier_id: string | null;
  received_by: string | null;
  received_date: string;
  status: string;
  notes: string | null;
  created_at: string;
  updated_at: string;
  purchase_order?: {
    id: string;
    po_number: string;
    supplier_id: string | null;
  };
  supplier?: {
    id: string;
    name: string;
  };
  receiver?: {
    id: string;
    full_name: string;
  };
  items?: GRNItem[];
}

export function useGRNs(poId?: string) {
  return useQuery({
    queryKey: ['grns', poId],
    queryFn: async () => {
      let query = supabase
        .from('goods_receipt_notes')
        .select(`
          *,
          purchase_order:purchase_orders(id, po_number, supplier_id),
          supplier:suppliers(id, name),
          receiver:profiles!goods_receipt_notes_received_by_fkey(id, full_name)
        `)
        .order('created_at', { ascending: false });

      if (poId) {
        query = query.eq('po_id', poId);
      }

      const { data, error } = await query;
      if (error) throw error;
      return data as GoodsReceiptNote[];
    },
  });
}

export function useGRN(id: string | undefined) {
  return useQuery({
    queryKey: ['grns', id],
    enabled: !!id,
    queryFn: async () => {
      const { data, error } = await supabase
        .from('goods_receipt_notes')
        .select(`
          *,
          purchase_order:purchase_orders(id, po_number, supplier_id),
          supplier:suppliers(id, name),
          receiver:profiles!goods_receipt_notes_received_by_fkey(id, full_name),
          items:grn_items(*, product:products(id, name, unit))
        `)
        .eq('id', id!)
        .maybeSingle();

      if (error) throw error;
      return data as GoodsReceiptNote | null;
    },
  });
}

interface CreateGRNData {
  po_id: string;
  supplier_id: string | null;
  received_date?: string;
  notes?: string;
  items: {
    po_item_id: string;
    product_id: string | null;
    ordered_quantity: number;
    received_quantity: number;
    accepted_quantity: number;
    rejected_quantity: number;
    rejection_reason?: string;
    batch_number?: string;
    notes?: string;
  }[];
}

export function useCreateGRN() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (data: CreateGRNData) => {
      const { data: userData } = await supabase.auth.getUser();
      const userId = userData.user?.id;

      const { items, ...grnData } = data;

      // Create GRN
      const { data: grn, error: grnError } = await supabase
        .from('goods_receipt_notes')
        .insert({
          ...grnData,
          grn_number: '', // Auto-generated by trigger
          received_by: userId,
          received_date: grnData.received_date || new Date().toISOString().split('T')[0],
        })
        .select()
        .single();

      if (grnError) throw grnError;

      // Insert GRN items
      const grnItems = items.map(item => ({
        grn_id: grn.id,
        ...item,
      }));

      const { error: itemsError } = await supabase
        .from('grn_items')
        .insert(grnItems);

      if (itemsError) throw itemsError;

      // Update PO item received quantities
      for (const item of items) {
        const { data: poItem } = await supabase
          .from('purchase_order_items')
          .select('received_quantity')
          .eq('id', item.po_item_id)
          .single();

        if (poItem) {
          await supabase
            .from('purchase_order_items')
            .update({
              received_quantity: (poItem.received_quantity || 0) + item.accepted_quantity,
            })
            .eq('id', item.po_item_id);
        }
      }

      return grn;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['grns'] });
      queryClient.invalidateQueries({ queryKey: ['purchase-orders'] });
      toast.success('Goods receipt recorded successfully');
    },
    onError: (error: Error) => {
      toast.error('Failed to record goods receipt: ' + error.message);
    },
  });
}

export function useVerifyGRN() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (grnId: string) => {
      // Get GRN with items
      const { data: grn, error: fetchError } = await supabase
        .from('goods_receipt_notes')
        .select(`
          *,
          items:grn_items(*)
        `)
        .eq('id', grnId)
        .single();

      if (fetchError) throw fetchError;

      // Update GRN status
      const { error: updateError } = await supabase
        .from('goods_receipt_notes')
        .update({ status: 'verified' })
        .eq('id', grnId);

      if (updateError) throw updateError;

      // Update inventory for each accepted item
      for (const item of (grn.items || [])) {
        if (item.accepted_quantity > 0) {
          // Get current inventory
          const { data: inventory } = await supabase
            .from('inventory')
            .select('id, quantity')
            .eq('product_id', item.product_id)
            .maybeSingle();

          if (inventory) {
            await supabase
              .from('inventory')
              .update({
                quantity: inventory.quantity + item.accepted_quantity,
                last_restocked_at: new Date().toISOString(),
              })
              .eq('id', inventory.id);
          } else {
            // Create inventory record - need to get a default office
            const { data: defaultOffice } = await supabase
              .from('offices')
              .select('id')
              .limit(1)
              .single();

            if (defaultOffice) {
              await supabase
                .from('inventory')
                .insert({
                  product_id: item.product_id,
                  office_id: defaultOffice.id,
                  quantity: item.accepted_quantity,
                  last_restocked_at: new Date().toISOString(),
                });
            }
          }

          // Create stock movement
          const { data: userData } = await supabase.auth.getUser();
          const { data: defaultOffice } = await supabase
            .from('offices')
            .select('id')
            .limit(1)
            .single();

          if (defaultOffice) {
            await supabase
              .from('stock_movements')
              .insert({
                product_id: item.product_id,
                office_id: defaultOffice.id,
                movement_type: 'in',
                quantity: item.accepted_quantity,
                reference_type: 'grn',
                reference_id: grnId,
                notes: `GRN: ${grn.grn_number}`,
                created_by: userData.user?.id,
              });
          }
        }
      }

      // Check if PO is fully delivered and update PO status
      const { data: poItems } = await supabase
        .from('purchase_order_items')
        .select('quantity, received_quantity')
        .eq('po_id', grn.po_id);

      const allDelivered = poItems?.every(item => item.received_quantity >= item.quantity);
      const partiallyDelivered = poItems?.some(item => item.received_quantity > 0 && item.received_quantity < item.quantity);

      if (allDelivered) {
        await supabase
          .from('purchase_orders')
          .update({ status: 'delivered' })
          .eq('id', grn.po_id);
      } else if (partiallyDelivered) {
        await supabase
          .from('purchase_orders')
          .update({ status: 'partial' })
          .eq('id', grn.po_id);
      }

      // Get linked sales order and update its status
      const { data: po } = await supabase
        .from('purchase_orders')
        .select('*')
        .eq('id', grn.po_id)
        .single();

      const salesOrderId = (po as any)?.sales_order_id;

      if (salesOrderId) {
        // Update sales order to partially_fulfilled when GRN is verified
        await supabase
          .from('sales_orders')
          .update({ status: 'partially_fulfilled' })
          .eq('id', salesOrderId)
          .in('status', ['in_procurement', 'ready_for_procurement']);
      }

      return { ...grn, sales_order_id: salesOrderId };
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ['grns'] });
      queryClient.invalidateQueries({ queryKey: ['purchase-orders'] });
      queryClient.invalidateQueries({ queryKey: ['inventory'] });
      queryClient.invalidateQueries({ queryKey: ['stock-movements'] });
      queryClient.invalidateQueries({ queryKey: ['sales-orders'] });
      if (data?.sales_order_id) {
        queryClient.invalidateQueries({ queryKey: ['sales-order-by-lead'] });
        queryClient.invalidateQueries({ queryKey: ['linked-grns'] });
      }
      toast.success('GRN verified and inventory updated');
    },
    onError: (error: Error) => {
      toast.error('Failed to verify GRN: ' + error.message);
    },
  });
}

export function useDeleteGRN() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase
        .from('goods_receipt_notes')
        .delete()
        .eq('id', id);
      if (error) throw error;
      return id;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['grns'] });
      toast.success('GRN deleted successfully');
    },
    onError: (error: Error) => {
      toast.error('Failed to delete GRN: ' + error.message);
    },
  });
}
